---
- name: "Download Kibana's deb"
  get_url:
    url: "https://artifacts.elastic.co/downloads/kibana/kibana-{{ kibana_new_version }}-amd64.deb"
    dest: "files/kibana-{{ kibana_new_version }}-amd64.deb"
    validate_certs: false
  delegate_to: localhost
  register: download_kibana
  until: download_kibana is succeeded
  when: kibana_install_type == 'remote'
- name: Copy Kibana to manage host
  delegate_to: "{{ hostvars['kbn-debian']['ansible_host'] }}"
  copy:
    src: "files/kibana-{{ kibana_new_version }}-amd64.deb"
    mode: 0755
    dest: "/tmp/kibana-{{ kibana_new_version }}-amd64.deb"
- name: Install Kibana
  delegate_to: "{{ hostvars['kbn-debian']['ansible_host'] }}"
  become: true
  apt:
    deb: "/tmp/kibana-{{ kibana_new_version }}-amd64.deb"
    state: present
- name: Configure Kibana
  delegate_to: "{{ hostvars['kbn-debian']['ansible_host'] }}"
  become: true
  template:
    src: kibana.yml.j2
    mode: 0644
    dest: /etc/kibana/kibana.yml
  notify: restart Kibana Debian
