---
- name: "Download Logstash's rpm"
  get_url:
    url: "https://artifacts.elastic.co/downloads/logstash/logstash-{{ logstash_new_version }}-x86_64.rpm"
    dest: "files/logstash-{{ logstash_new_version }}-x86_64.rpm"
    validate_certs: false
  register: download_logstash
  delegate_to: localhost
  until: download_logstash is succeeded
  when: logstash_install_type == 'remote'
- name: Copy Logstash to managed node
  copy:
    src: "files/logstash-{{ logstash_new_version }}-x86_64.rpm"
    mode: 0755
    dest: "/tmp/logstash-{{ logstash_new_version }}-x86_64.rpm"
- name: Install Logstash
  become: true
  yum:
    name: "/tmp/logstash-{{ logstash_new_version }}-x86_64.rpm"
    state: present
- name: Configure Logstash
  become: true
  template:
    src: logstash.yml.j2
    mode: 0644
    dest: /etc/logstash/logstash.yml
- name: Configure run script file
  become: true
  template:
    src: logstash.sh.j2
    mode: "0744"
    owner: root
    dest: /etc/logstash/logstash.sh
- name: Configure init file
  become: true
  template:
    src: logstash.service.j2
    mode: "0744"
    owner: root
    dest: /etc/systemd/system/logstash.service
  notify: restart Logstash
