---
- name: "Download Kibana's rpm"
  get_url:
    url: "https://artifacts.elastic.co/downloads/kibana/kibana-{{ kibana_new_version }}-x86_64.rpm"
    dest: "files/kibana-{{ kibana_new_version }}-x86_64.rpm"
    validate_certs: false
  register: download_kibana
  delegate_to: localhost
  until: download_kibana is succeeded
  when: kibana_install_type == 'remote'
- name: Copy Kibana to managed node
  delegate_to: "{{ hostvars['kbn-centos']['ansible_host'] }}"
  copy:
    src: "files/kibana-{{ kibana_new_version }}-x86_64.rpm"
    mode: 0755
    dest: "/tmp/kibana-{{ kibana_new_version }}-x86_64.rpm"
- name: Install Kibana
  delegate_to: "{{ hostvars['kbn-centos']['ansible_host'] }}"
  become: true
  yum:
    name: "/tmp/kibana-{{ kibana_new_version }}-x86_64.rpm"
    state: present
- name: Configure Kibana
  delegate_to: "{{ hostvars['kbn-centos']['ansible_host'] }}"
  become: true
  template:
    src: kibana.yml.j2
    mode: 0644
    dest: /etc/kibana/kibana.yml
  notify: restart Kibana Centos