---
- name: "Download Kibana's rpm"
  get_url:
    url: "https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{{ filebeat_new_version }}-x86_64.rpm"
    dest: "files/filebeat-{{ filebeat_new_version }}-x86_64.rpm"
    validate_certs: false
  register: download_filebeat
  delegate_to: localhost
  until: download_filebeat is succeeded
  when: filebeat_install_type == 'remote'
- name: Copy Filebeat to managed node
  delegate_to: "{{ hostvars['fb-centos']['ansible_host'] }}"
  copy:
    src: "files/filebeat-{{ filebeat_new_version }}-x86_64.rpm"
    mode: 0755
    dest: "/tmp/filebeat-{{ filebeat_new_version }}-x86_64.rpm"
- name: Install Filebeat
  delegate_to: "{{ hostvars['fb-centos']['ansible_host'] }}"
  become: true
  yum:
    name: "/tmp/filebeat-{{ filebeat_new_version }}-x86_64.rpm"
    state: present
- name: Configure Filebeat
  delegate_to: "{{ hostvars['fb-centos']['ansible_host'] }}"
  become: true
  template:
    src: filebeat.yml.j2
    mode: 0644
    dest: /etc/filebeat/filebeat.yml
  notify: restart Filebeat Centos
- name: Set filebeat systemwork
  delegate_to: "{{ hostvars['fb-centos']['ansible_host'] }}"
  become: true
  command:
    cmd: filebeat modules enable system
    chdir: /usr/share/filebeat/bin
  register: filebeat_modules
  changed_when: filebeat_modules.stdout != 'Module system is already enabled'
- name: Load kibana dashboard
  delegate_to: "{{ hostvars['fb-centos']['ansible_host'] }}"
  become: true
  command:
    cmd: filebeat setup
    chdir: /usr/share/filebeat/bin
  register: filebeat_setup
  until: filebeat_setup is succeeded
