---
- name: restart Elasticsearch
  become: true
  service:
    name: elasticsearch
    state: restarted
  when: ansible_virtualization_type != 'docker'

- name: restart Logstash
  become: true
  service:
    name: logstash
    state: restarted
  when: ansible_virtualization_type != 'docker'

